language: python
sudo: false

python:
  - "2.6"
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libffi-dev
      - libssl-dev
      - python-dev
      - python-pip # Standin for python-setuptools, a build-dep of M2Crypto
      - swig

install:
  - pip install --disable-pip-version-check --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install -e .

script:
  - coverage run setup.py test

after_success:
  - coveralls
